import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Title from '../pages/Components/Title'
import Header from './Components/Header'
import About from './Components/About'
import Point from './Components/Point'
import Footer from './Components/Footer'
import Infomation from './Components/Infomation'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"></link>
      </Head>

      <main className={styles.main}>
          <Header/>
          <Title/>
          <About />
          <Infomation />
          <Point />
          <Footer />
          
      </main>


    </div>
  )
}
