import Head from 'next/head'
import Title from '../pages/Components/Title'
import Header from './Components/Header'
import About from './Components/About'
import Point from './Components/Point'
import Footer from './Components/Footer'
import Infomation from './Components/Infomation'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="apple-mobile-web-app-title" content="CSS Hamburger Menu" />      </Head>

      <div style={{ backgroundColor: ` rgb(201, 189, 151)` }}>
        <Header />
        <Title />
        <About />
        <Infomation />
        <Point />
        <Footer />
        <h1 className="media">機種判定</h1>
      </div>
    </>
  )
}
